name: expatrio_challenge
description: Expatrio challenge.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  http: ^1.2.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
     - assets/images/logo/
     - assets/images/cliparts/

  fonts:
       - family: Acumin Pro
         fonts:
            - asset: assets/fonts/Acumin-RPro.otf
            - asset: assets/fonts/Acumin-BdPro.otf
              weight: 700

            - asset: assets/fonts/Acumin-ItPro.otf
              style: italic

