List<Map<String, String>> countriesList = [
  {"name": "Afghanistan", "codeName": "AF"},
  {"name": "Åland Islands", "codeName": "AX"},
  {"name": "Albania", "codeName": "AL"},
  {"name": "Algeria", "codeName": "DZ"},
  {"name": "American Samoa", "codeName": "AS"},
  {"name": "AndorrA", "codeName": "AD"},
  {"name": "Angola", "codeName": "AO"},
  {"name": "Anguilla", "codeName": "AI"},
  {"name": "Antarctica", "codeName": "AQ"},
  {"name": "Antigua and Barbuda", "codeName": "AG"},
  {"name": "Argentina", "codeName": "AR"},
  {"name": "Armenia", "codeName": "AM"},
  {"name": "Aruba", "codeName": "AW"},
  {"name": "Australia", "codeName": "AU"},
  {"name": "Austria", "codeName": "AT"},
  {"name": "Azerbaijan", "codeName": "AZ"},
  {"name": "Bahamas", "codeName": "BS"},
  {"name": "Bahrain", "codeName": "BH"},
  {"name": "Bangladesh", "codeName": "BD"},
  {"name": "Barbados", "codeName": "BB"},
  {"name": "Belarus", "codeName": "BY"},
  {"name": "Belgium", "codeName": "BE"},
  {"name": "Belize", "codeName": "BZ"},
  {"name": "Benin", "codeName": "BJ"},
  {"name": "Bermuda", "codeName": "BM"},
  {"name": "Bhutan", "codeName": "BT"},
  {"name": "Bolivia", "codeName": "BO"},
  {"name": "Bosnia and Herzegovina", "codeName": "BA"},
  {"name": "Botswana", "codeName": "BW"},
  {"name": "Bouvet Island", "codeName": "BV"},
  {"name": "Brazil", "codeName": "BR"},
  {"name": "British Indian Ocean Territory", "codeName": "IO"},
  {"name": "Brunei Darussalam", "codeName": "BN"},
  {"name": "Bulgaria", "codeName": "BG"},
  {"name": "Burkina Faso", "codeName": "BF"},
  {"name": "Burundi", "codeName": "BI"},
  {"name": "Cambodia", "codeName": "KH"},
  {"name": "Cameroon", "codeName": "CM"},
  {"name": "Canada", "codeName": "CA"},
  {"name": "Cape Verde", "codeName": "CV"},
  {"name": "Cayman Islands", "codeName": "KY"},
  {"name": "Central African Republic", "codeName": "CF"},
  {"name": "Chad", "codeName": "TD"},
  {"name": "Chile", "codeName": "CL"},
  {"name": "China", "codeName": "CN"},
  {"name": "Christmas Island", "codeName": "CX"},
  {"name": "Cocos (Keeling) Islands", "codeName": "CC"},
  {"name": "Colombia", "codeName": "CO"},
  {"name": "Comoros", "codeName": "KM"},
  {"name": "Congo", "codeName": "CG"},
  {"name": "Congo, The Democratic Republic of the", "codeName": "CD"},
  {"name": "Cook Islands", "codeName": "CK"},
  {"name": "Costa Rica", "codeName": "CR"},
  {"name": "Croatia", "codeName": "HR"},
  {"name": "Cuba", "codeName": "CU"},
  {"name": "Cyprus", "codeName": "CY"},
  {"name": "Czech Republic", "codeName": "CZ"},
  {"name": "Denmark", "codeName": "DK"},
  {"name": "Djibouti", "codeName": "DJ"},
  {"name": "Dominica", "codeName": "DM"},
  {"name": "Dominican Republic", "codeName": "DO"},
  {"name": "Ecuador", "codeName": "EC"},
  {"name": "Egypt", "codeName": "EG"},
  {"name": "El Salvador", "codeName": "SV"},
  {"name": "Equatorial Guinea", "codeName": "GQ"},
  {"name": "Eritrea", "codeName": "ER"},
  {"name": "Estonia", "codeName": "EE"},
  {"name": "Ethiopia", "codeName": "ET"},
  {"name": "Falkland Islands (Malvinas)", "codeName": "FK"},
  {"name": "Faroe Islands", "codeName": "FO"},
  {"name": "Fiji", "codeName": "FJ"},
  {"name": "Finland", "codeName": "FI"},
  {"name": "France", "codeName": "FR"},
  {"name": "French Guiana", "codeName": "GF"},
  {"name": "French Polynesia", "codeName": "PF"},
  {"name": "French Southern Territories", "codeName": "TF"},
  {"name": "Gabon", "codeName": "GA"},
  {"name": "Gambia", "codeName": "GM"},
  {"name": "Georgia", "codeName": "GE"},
  {"name": "Germany", "codeName": "DE"},
  {"name": "Ghana", "codeName": "GH"},
  {"name": "Gibraltar", "codeName": "GI"},
  {"name": "Greece", "codeName": "GR"},
  {"name": "Greenland", "codeName": "GL"},
  {"name": "Grenada", "codeName": "GD"},
  {"name": "Guadeloupe", "codeName": "GP"},
  {"name": "Guam", "codeName": "GU"},
  {"name": "Guatemala", "codeName": "GT"},
  {"name": "Guernsey", "codeName": "GG"},
  {"name": "Guinea", "codeName": "GN"},
  {"name": "Guinea-Bissau", "codeName": "GW"},
  {"name": "Guyana", "codeName": "GY"},
  {"name": "Haiti", "codeName": "HT"},
  {"name": "Heard Island and Mcdonald Islands", "codeName": "HM"},
  {"name": "Holy See (Vatican City State)", "codeName": "VA"},
  {"name": "Honduras", "codeName": "HN"},
  {"name": "Hong Kong", "codeName": "HK"},
  {"name": "Hungary", "codeName": "HU"},
  {"name": "Iceland", "codeName": "IS"},
  {"name": "India", "codeName": "IN"},
  {"name": "Indonesia", "codeName": "ID"},
  {"name": "Iran, Islamic Republic Of", "codeName": "IR"},
  {"name": "Iraq", "codeName": "IQ"},
  {"name": "Ireland", "codeName": "IE"},
  {"name": "Isle of Man", "codeName": "IM"},
  {"name": "Israel", "codeName": "IL"},
  {"name": "Italy", "codeName": "IT"},
  {"name": "Jamaica", "codeName": "JM"},
  {"name": "Japan", "codeName": "JP"},
  {"name": "Jersey", "codeName": "JE"},
  {"name": "Jordan", "codeName": "JO"},
  {"name": "Kazakhstan", "codeName": "KZ"},
  {"name": "Kenya", "codeName": "KE"},
  {"name": "Kiribati", "codeName": "KI"},
  {"name": "Korea, Republic of", "codeName": "KR"},
  {"name": "Kuwait", "codeName": "KW"},
  {"name": "Kyrgyzstan", "codeName": "KG"},
  {"name": "Latvia", "codeName": "LV"},
  {"name": "Lebanon", "codeName": "LB"},
  {"name": "Lesotho", "codeName": "LS"},
  {"name": "Liberia", "codeName": "LR"},
  {"name": "Libyan Arab Jamahiriya", "codeName": "LY"},
  {"name": "Liechtenstein", "codeName": "LI"},
  {"name": "Lithuania", "codeName": "LT"},
  {"name": "Luxembourg", "codeName": "LU"},
  {"name": "Macao", "codeName": "MO"},
  {"name": "North Macedonia", "codeName": "MK"},
  {"name": "Madagascar", "codeName": "MG"},
  {"name": "Malawi", "codeName": "MW"},
  {"name": "Malaysia", "codeName": "MY"},
  {"name": "Maldives", "codeName": "MV"},
  {"name": "Mali", "codeName": "ML"},
  {"name": "Malta", "codeName": "MT"},
  {"name": "Marshall Islands", "codeName": "MH"},
  {"name": "Martinique", "codeName": "MQ"},
  {"name": "Mauritania", "codeName": "MR"},
  {"name": "Mauritius", "codeName": "MU"},
  {"name": "Mayotte", "codeName": "YT"},
  {"name": "Mexico", "codeName": "MX"},
  {"name": "Micronesia, Federated States of", "codeName": "FM"},
  {"name": "Moldova, Republic of", "codeName": "MD"},
  {"name": "Monaco", "codeName": "MC"},
  {"name": "Mongolia", "codeName": "MN"},
  {"name": "Montserrat", "codeName": "MS"},
  {"name": "Morocco", "codeName": "MA"},
  {"name": "Mozambique", "codeName": "MZ"},
  {"name": "Myanmar", "codeName": "MM"},
  {"name": "Namibia", "codeName": "NA"},
  {"name": "Nauru", "codeName": "NR"},
  {"name": "Nepal", "codeName": "NP"},
  {"name": "Netherlands", "codeName": "NL"},
  {"name": "Netherlands Antilles", "codeName": "AN"},
  {"name": "New Caledonia", "codeName": "NC"},
  {"name": "New Zealand", "codeName": "NZ"},
  {"name": "Nicaragua", "codeName": "NI"},
  {"name": "Niger", "codeName": "NE"},
  {"name": "Nigeria", "codeName": "NG"},
  {"name": "Niue", "codeName": "NU"},
  {"name": "Norfolk Island", "codeName": "NF"},
  {"name": "Northern Mariana Islands", "codeName": "MP"},
  {"name": "Norway", "codeName": "NO"},
  {"name": "Oman", "codeName": "OM"},
  {"name": "Pakistan", "codeName": "PK"},
  {"name": "Palau", "codeName": "PW"},
  {"name": "Palestinian Territory, Occupied", "codeName": "PS"},
  {"name": "Panama", "codeName": "PA"},
  {"name": "Papua New Guinea", "codeName": "PG"},
  {"name": "Paraguay", "codeName": "PY"},
  {"name": "Peru", "codeName": "PE"},
  {"name": "Philippines", "codeName": "PH"},
  {"name": "Pitcairn Islands", "codeName": "PN"},
  {"name": "Poland", "codeName": "PL"},
  {"name": "Portugal", "codeName": "PT"},
  {"name": "Puerto Rico", "codeName": "PR"},
  {"name": "Qatar", "codeName": "QA"},
  {"name": "Reunion", "codeName": "RE"},
  {"name": "Romania", "codeName": "RO"},
  {"name": "Russian Federation", "codeName": "RU"},
  {"name": "Rwanda", "codeName": "RW"},
  {"name": "Saint Helena", "codeName": "SH"},
  {"name": "Saint Kitts and Nevis", "codeName": "KN"},
  {"name": "Saint Lucia", "codeName": "LC"},
  {"name": "Saint Pierre and Miquelon", "codeName": "PM"},
  {"name": "Saint Vincent and the Grenadines", "codeName": "VC"},
  {"name": "Samoa", "codeName": "WS"},
  {"name": "San Marino", "codeName": "SM"},
  {"name": "Sao Tome and Principe", "codeName": "ST"},
  {"name": "Saudi Arabia", "codeName": "SA"},
  {"name": "Senegal", "codeName": "SN"},
  {"name": "Serbia and Montenegro", "codeName": "CS"},
  {"name": "Seychelles", "codeName": "SC"},
  {"name": "Sierra Leone", "codeName": "SL"},
  {"name": "Singapore", "codeName": "SG"},
  {"name": "Slovakia", "codeName": "SK"},
  {"name": "Slovenia", "codeName": "SI"},
  {"name": "Solomon Islands", "codeName": "SB"},
  {"name": "Somalia", "codeName": "SO"},
  {"name": "South Africa", "codeName": "ZA"},
  {"name": "South Georgia and the South Sandwich Islands", "codeName": "GS"},
  {"name": "Spain", "codeName": "ES"},
  {"name": "Sri Lanka", "codeName": "LK"},
  {"name": "Sudan", "codeName": "SD"},
  {"name": "Suriname", "codeName": "SR"},
  {"name": "Svalbard and Jan Mayen", "codeName": "SJ"},
  {"name": "Swaziland", "codeName": "SZ"},
  {"name": "Sweden", "codeName": "SE"},
  {"name": "Switzerland", "codeName": "CH"},
  {"name": "Syrian Arab Republic", "codeName": "SY"},
  {"name": "Taiwan", "codeName": "TW"},
  {"name": "Tajikistan", "codeName": "TJ"},
  {"name": "Tanzania, United Republic of", "codeName": "TZ"},
  {"name": "Thailand", "codeName": "TH"},
  {"name": "Timor-Leste", "codeName": "TL"},
  {"name": "Togo", "codeName": "TG"},
  {"name": "Tokelau", "codeName": "TK"},
  {"name": "Tonga", "codeName": "TO"},
  {"name": "Trinidad and Tobago", "codeName": "TT"},
  {"name": "Tunisia", "codeName": "TN"},
  {"name": "Turkey", "codeName": "TR"},
  {"name": "Turkmenistan", "codeName": "TM"},
  {"name": "Turks and Caicos Islands", "codeName": "TC"},
  {"name": "Tuvalu", "codeName": "TV"},
  {"name": "Uganda", "codeName": "UG"},
  {"name": "Ukraine", "codeName": "UA"},
  {"name": "United Arab Emirates", "codeName": "AE"},
  {"name": "United Kingdom", "codeName": "GB"},
  {"name": "United States", "codeName": "US"},
  {"name": "United States Minor Outlying Islands", "codeName": "UM"},
  {"name": "Uruguay", "codeName": "UY"},
  {"name": "Uzbekistan", "codeName": "UZ"},
  {"name": "Vanuatu", "codeName": "VU"},
  {"name": "Venezuela", "codeName": "VE"},
  {"name": "Vietnam", "codeName": "VN"},
  {"name": "Virgin Islands, British", "codeName": "VG"},
  {"name": "Virgin Islands, U.S.", "codeName": "VI"},
  {"name": "Wallis and Futuna", "codeName": "WF"},
  {"name": "Western Sahara", "codeName": "EH"},
  {"name": "Yemen", "codeName": "YE"},
  {"name": "Zambia", "codeName": "ZM"},
  {"name": "Zimbabwe", "codeName": "ZN"}
];
