List<Map<String, String>> countriesList = [
  {'name': 'Afghanistan', 'codeName': 'AF'},
  {'name': 'Albania', 'codeName': 'AL'},
  {'name': 'Algeria', 'codeName': 'DZ'},
  {'name': 'Andorra', 'codeName': 'AD'},
  {'name': 'Angola', 'codeName': 'AO'},
  {'name': 'Antigua and Barbuda', 'codeName': 'AG'},
  {'name': 'Argentina', 'codeName': 'AR'},
  {'name': 'Armenia', 'codeName': 'AM'},
  {'name': 'Australia', 'codeName': 'AU'},
  {'name': 'Austria', 'codeName': 'AT'},
  {'name': 'Azerbaijan', 'codeName': 'AZ'},
  {'name': 'Bahamas', 'codeName': 'BS'},
  {'name': 'Bahrain', 'codeName': 'BH'},
  {'name': 'Bangladesh', 'codeName': 'BD'},
  {'name': 'Barbados', 'codeName': 'BB'},
  {'name': 'Belarus', 'codeName': 'BY'},
  {'name': 'Belgium', 'codeName': 'BE'},
  {'name': 'Belize', 'codeName': 'BZ'},
  {'name': 'Benin', 'codeName': 'BJ'},
  {'name': 'Bhutan', 'codeName': 'BT'},
  {'name': 'Bolivia', 'codeName': 'BO'},
  {'name': 'Bosnia and Herzegovina', 'codeName': 'BA'},
  {'name': 'Botswana', 'codeName': 'BW'},
  {'name': 'Brazil', 'codeName': 'BR'},
  {'name': 'Brunei', 'codeName': 'BN'},
  {'name': 'Bulgaria', 'codeName': 'BG'},
  {'name': 'Burkina Faso', 'codeName': 'BF'},
  {'name': 'Burundi', 'codeName': 'BI'},
  {'name': 'Cabo Verde', 'codeName': 'CV'},
  {'name': 'Cambodia', 'codeName': 'KH'},
  {'name': 'Cameroon', 'codeName': 'CM'},
  {'name': 'Canada', 'codeName': 'CA'},
  {'name': 'Central African Republic', 'codeName': 'CF'},
  {'name': 'Chad', 'codeName': 'TD'},
  {'name': 'Chile', 'codeName': 'CL'},
  {'name': 'China', 'codeName': 'CN'},
  {'name': 'Colombia', 'codeName': 'CO'},
  {'name': 'Comoros', 'codeName': 'KM'},
  {'name': 'Congo (Congo-Brazzaville)', 'codeName': 'CG'},
  {'name': 'Costa Rica', 'codeName': 'CR'},
  {'name': 'Croatia', 'codeName': 'HR'},
  {'name': 'Cuba', 'codeName': 'CU'},
  {'name': 'Cyprus', 'codeName': 'CY'},
  {'name': 'Czechia (Czech Republic)', 'codeName': 'CZ'},
  {'name': 'Democratic Republic of the Congo', 'codeName': 'CD'},
  {'name': 'Denmark', 'codeName': 'DK'},
  {'name': 'Djibouti', 'codeName': 'DJ'},
  {'name': 'Dominica', 'codeName': 'DM'},
  {'name': 'Dominican Republic', 'codeName': 'DO'},
  {'name': 'Ecuador', 'codeName': 'EC'},
  {'name': 'Egypt', 'codeName': 'EG'},
  {'name': 'El Salvador', 'codeName': 'SV'},
  {'name': 'Equatorial Guinea', 'codeName': 'GQ'},
  {'name': 'Eritrea', 'codeName': 'ER'},
  {'name': 'Estonia', 'codeName': 'EE'},
  {'name': 'Eswatini (fmr. "Swaziland")', 'codeName': 'SZ'},
  {'name': 'Ethiopia', 'codeName': 'ET'},
  {'name': 'Fiji', 'codeName': 'FJ'},
  {'name': 'Finland', 'codeName': 'FI'},
  {'name': 'France', 'codeName': 'FR'},
  {'name': 'Gabon', 'codeName': 'GA'},
  {'name': 'Gambia', 'codeName': 'GM'},
  {'name': 'Georgia', 'codeName': 'GE'},
  {'name': 'Germany', 'codeName': 'DE'},
  {'name': 'Ghana', 'codeName': 'GH'},
  {'name': 'Greece', 'codeName': 'GR'},
  {'name': 'Grenada', 'codeName': 'GD'},
  {'name': 'Guatemala', 'codeName': 'GT'},
  {'name': 'Guinea', 'codeName': 'GN'},
  {'name': 'Guinea-Bissau', 'codeName': 'GW'},
  {'name': 'Guyana', 'codeName': 'GY'},
  {'name': 'Haiti', 'codeName': 'HT'},
  {'name': 'Holy See', 'codeName': 'VA'},
  {'name': 'Honduras', 'codeName': 'HN'},
  {'name': 'Hungary', 'codeName': 'HU'},
  {'name': 'Iceland', 'codeName': 'IS'},
  {'name': 'India', 'codeName': 'IN'},
  {'name': 'Indonesia', 'codeName': 'ID'},
  {'name': 'Iran', 'codeName': 'IR'},
  {'name': 'Iraq', 'codeName': 'IQ'},
  {'name': 'Ireland', 'codeName': 'IE'},
  {'name': 'Israel', 'codeName': 'IL'},
  {'name': 'Italy', 'codeName': 'IT'},
  {'name': 'Jamaica', 'codeName': 'JM'},
  {'name': 'Japan', 'codeName': 'JP'},
  {'name': 'Jordan', 'codeName': 'JO'},
  {'name': 'Kazakhstan', 'codeName': 'KZ'},
  {'name': 'Kenya', 'codeName': 'KE'},
  {'name': 'Kiribati', 'codeName': 'KI'},
  {'name': 'Kuwait', 'codeName': 'KW'},
  {'name': 'Kyrgyzstan', 'codeName': 'KG'},
  {'name': 'Laos', 'codeName': 'LA'},
  {'name': 'Latvia', 'codeName': 'LV'},
  {'name': 'Lebanon', 'codeName': 'LB'},
  {'name': 'Lesotho', 'codeName': 'LS'},
  {'name': 'Liberia', 'codeName': 'LR'},
  {'name': 'Libya', 'codeName': 'LY'},
  {'name': 'Liechtenstein', 'codeName': 'LI'},
  {'name': 'Lithuania', 'codeName': 'LT'},
  {'name': 'Luxembourg', 'codeName': 'LU'},
  {'name': 'Madagascar', 'codeName': 'MG'},
  {'name': 'Malawi', 'codeName': 'MW'},
  {'name': 'Malaysia', 'codeName': 'MY'},
  {'name': 'Maldives', 'codeName': 'MV'},
  {'name': 'Mali', 'codeName': 'ML'},
  {'name': 'Malta', 'codeName': 'MT'},
  {'name': 'Marshall Islands', 'codeName': 'MH'},
  {'name': 'Mauritania', 'codeName': 'MR'},
  {'name': 'Mauritius', 'codeName': 'MU'},
  {'name': 'Mexico', 'codeName': 'MX'},
  {'name': 'Micronesia', 'codeName': 'FM'},
  {'name': 'Moldova', 'codeName': 'MD'},
  {'name': 'Monaco', 'codeName': 'MC'},
  {'name': 'Mongolia', 'codeName': 'MN'},
  {'name': 'Montenegro', 'codeName': 'ME'},
  {'name': 'Morocco', 'codeName': 'MA'},
  {'name': 'Mozambique', 'codeName': 'MZ'},
  {'name': 'Myanmar (formerly Burma)', 'codeName': 'MM'},
  {'name': 'Namibia', 'codeName': 'NA'},
  {'name': 'Nauru', 'codeName': 'NR'},
  {'name': 'Nepal', 'codeName': 'NP'},
  {'name': 'Netherlands', 'codeName': 'NL'},
  {'name': 'New Zealand', 'codeName': 'NZ'},
  {'name': 'Nicaragua', 'codeName': 'NI'},
  {'name': 'Niger', 'codeName': 'NE'},
  {'name': 'Nigeria', 'codeName': 'NG'},
  {'name': 'North Korea', 'codeName': 'KP'},
  {'name': 'North Macedonia (formerly Macedonia)', 'codeName': 'MK'},
  {'name': 'Norway', 'codeName': 'NO'},
  {'name': 'Oman', 'codeName': 'OM'},
  {'name': 'Pakistan', 'codeName': 'PK'},
  {'name': 'Palau', 'codeName': 'PW'},
  {'name': 'Palestine State', 'codeName': 'PS'},
  {'name': 'Panama', 'codeName': 'PA'},
  {'name': 'Papua New Guinea', 'codeName': 'PG'},
  {'name': 'Paraguay', 'codeName': 'PY'},
  {'name': 'Peru', 'codeName': 'PE'},
  {'name': 'Philippines', 'codeName': 'PH'},
  {'name': 'Poland', 'codeName': 'PL'},
  {'name': 'Portugal', 'codeName': 'PT'},
  {'name': 'Qatar', 'codeName': 'QA'},
  {'name': 'Romania', 'codeName': 'RO'},
  {'name': 'Russia', 'codeName': 'RU'},
  {'name': 'Rwanda', 'codeName': 'RW'},
  {'name': 'Saint Kitts and Nevis', 'codeName': 'KN'},
  {'name': 'Saint Lucia', 'codeName': 'LC'},
  {'name': 'Saint Vincent and the Grenadines', 'codeName': 'VC'},
  {'name': 'Samoa', 'codeName': 'WS'},
  {'name': 'San Marino', 'codeName': 'SM'},
  {'name': 'Sao Tome and Principe', 'codeName': 'ST'},
  {'name': 'Saudi Arabia', 'codeName': 'SA'},
  {'name': 'Senegal', 'codeName': 'SN'},
  {'name': 'Serbia', 'codeName': 'RS'},
  {'name': 'Seychelles', 'codeName': 'SC'},
  {'name': 'Sierra Leone', 'codeName': 'SL'},
  {'name': 'Singapore', 'codeName': 'SG'},
  {'name': 'Slovakia', 'codeName': 'SK'},
  {'name': 'Slovenia', 'codeName': 'SI'},
  {'name': 'Solomon Islands', 'codeName': 'SB'},
  {'name': 'Somalia', 'codeName': 'SO'},
  {'name': 'South Africa', 'codeName': 'ZA'},
  {'name': 'South Korea', 'codeName': 'KR'},
  {'name': 'South Sudan', 'codeName': 'SS'},
  {'name': 'Spain', 'codeName': 'ES'},
  {'name': 'Sri Lanka', 'codeName': 'LK'},
  {'name': 'Sudan', 'codeName': 'SD'},
  {'name': 'Suriname', 'codeName': 'SR'},
  {'name': 'Sweden', 'codeName': 'SE'},
  {'name': 'Switzerland', 'codeName': 'CH'},
  {'name': 'Syria', 'codeName': 'SY'},
  {'name': 'Taiwan', 'codeName': 'TW'},
  {'name': 'Tajikistan', 'codeName': 'TJ'},
  {'name': 'Tanzania', 'codeName': 'TZ'},
  {'name': 'Thailand', 'codeName': 'TH'},
  {'name': 'Timor-Leste', 'codeName': 'TL'},
  {'name': 'Togo', 'codeName': 'TG'},
  {'name': 'Tonga', 'codeName': 'TO'},
  {'name': 'Trinidad and Tobago', 'codeName': 'TT'},
  {'name': 'Tunisia', 'codeName': 'TN'},
  {'name': 'Turkey', 'codeName': 'TR'},
  {'name': 'Turkmenistan', 'codeName': 'TM'},
  {'name': 'Tuvalu', 'codeName': 'TV'},
  {'name': 'Uganda', 'codeName': 'UG'},
  {'name': 'Ukraine', 'codeName': 'UA'},
  {'name': 'United Arab Emirates', 'codeName': 'AE'},
  {'name': 'United Kingdom', 'codeName': 'GB'},
  {'name': 'United States of America', 'codeName': 'US'},
  {'name': 'Uruguay', 'codeName': 'UY'},
  {'name': 'Uzbekistan', 'codeName': 'UZ'},
  {'name': 'Vanuatu', 'codeName': 'VU'},
  {'name': 'Venezuela', 'codeName': 'VE'},
  {'name': 'Vietnam', 'codeName': 'VN'},
  {'name': 'Yemen', 'codeName': 'YE'},
  {'name': 'Zambia', 'codeName': 'ZM'},
  {'name': 'Zimbabwe', 'codeName': 'ZW'},
];
